### ISSUE TITLE
SSL Cert Issue at https://gw.sam.gov/

### ISSUE THREAD

**Issue by lrutker** [GSA/openIAE#24]
Go to https://www.whynopadlock.com/ and you will see why Chrome displays a cert error when displaying https://gw.sam.gov/SAMWS/1.0/Entity?wsdl . This was discovered when debugging why some environments curl and OpenSSL have issues reaching the site (I have not yet resolved that issue, and I am unsure of the underlying issue is the cert, though passing -k to curl telling it to ignore cert errors, bypasses the issues). While the cert expires at the end of the year, it should be regenerated earlier with a more modern cert.
Thanks

**Comment by aromero6** [comment]
Good morning,

Thanks for pointing this out.  This is something we are fully aware of and
are planning to have resolved by the end of November this year.  The
original certificates that were generated are SHA1 certs, while we are
planning on moving to SHA2 certs that will resolve the problem within
certain browsers, saying that we are not secured.

For now, please ignore those errors as the sites and certs are valid, but
again, it will be fully resolved by the end of November.

Thanks,
Tony


Antonio Romero
US Federal Government
General Services Administration OCIO
Office of Enterprise Infrastructure
O: 312.353.3116
C: 312.497.5592

**Comment by lrutker** [comment]
It looks like this can be closed with the new cert.
